//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenWeatherService.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenWeatherService.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Folder doesn&apos;t exist. Trying to create it. Folder: {1}.
        /// </summary>
        internal static string logMsg001 {
            get {
                return ResourceManager.GetString("logMsg001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging enabled. Folder Path: {1}.
        /// </summary>
        internal static string logMsg002 {
            get {
                return ResourceManager.GetString("logMsg002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create log folder. Logging disabled..
        /// </summary>
        internal static string logMsg003 {
            get {
                return ResourceManager.GetString("logMsg003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging disabled..
        /// </summary>
        internal static string logMsg004 {
            get {
                return ResourceManager.GetString("logMsg004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get log settings from web.config. Logging disabled..
        /// </summary>
        internal static string logMsg005 {
            get {
                return ResourceManager.GetString("logMsg005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writing to the log file. File Path: {1}.
        /// </summary>
        internal static string logMsg006 {
            get {
                return ResourceManager.GetString("logMsg006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ********************************************************************************.
        /// </summary>
        internal static string logTextLineSeparator {
            get {
                return ResourceManager.GetString("logTextLineSeparator", resourceCulture);
            }
        }
    }
}
